<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 red_apple.glb
Author: RPSebb (https://sketchfab.com/RPSebb)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/red-apple-7a179f2b4837457eafa66c2f7094d280
Title: Red Apple
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('3dModels/GLB/red_apple.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Apple_Cut_Low001_Apple_Baked_0.geometry}
          material={gltf.materials.Apple_Baked}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
